spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/transportae
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                formatsql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway: 
        enabled: true
        baseline-on-migrate: true
        baseline-description: "init"
        baseline-version: 0
        validate-on-migrate: true
