spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/transportae
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                formatsql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: mirer.rmj@gmail.com
        password: senhaSMTP
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
