server:
    port: 8080
    address: localhost
spring:
    application:
        name: transportae-core
    cloud:
        discovery:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/transportae
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                formatsql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        enabled: false
    mail:
        host: smtp.elasticemail.com
        port: 2525
        username: mirer.rmj@gmail.com
        password: senhaSMTP
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
